# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\"5\n\x16RecommendationsRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"[\n\x0eRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x0e\n\x06reason\x18\x05 \x01(\t\"M\n\x17RecommendationsResponse\x12\x32\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x19.analytics.Recommendation2o\n\x10\x41nalyticsService\x12[\n\x12GetRecommendations\x12!.analytics.RecommendationsRequest\x1a\".analytics.RecommendationsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONSREQUEST']._serialized_start=30
  _globals['_RECOMMENDATIONSREQUEST']._serialized_end=83
  _globals['_RECOMMENDATION']._serialized_start=85
  _globals['_RECOMMENDATION']._serialized_end=176
  _globals['_RECOMMENDATIONSRESPONSE']._serialized_start=178
  _globals['_RECOMMENDATIONSRESPONSE']._serialized_end=255
  _globals['_ANALYTICSSERVICE']._serialized_start=257
  _globals['_ANALYTICSSERVICE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
